[general]
show_welcome = false
skip_boot_anim = true

[general.updates]
check = false

[display.ui]
show_menubar = false

[input]
auto_bind = false

[input.bindings]
port1 = 'keyboard'
port1_driver = 'usb-xbox-gamepad'

[net]
enable = false
