namespace XemuTestRunner.Networking;

internal static class EvidencePage
{
    public const string Html = """
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Test evidence</title>
<style>
:root{color-scheme:dark}[hidden]{display:none!important}body{font:14px system-ui;background:#101216;color:#e7ebf0;margin:24px}a{color:#8bc3ff}button,select,input{background:#242a34;color:inherit;padding:7px;border:1px solid #485466;border-radius:5px}button{cursor:pointer}table{border-collapse:collapse;width:100%;margin:16px 0}td,th{border-bottom:1px solid #323a46;padding:8px;text-align:left;vertical-align:top}pre{background:#181d25;border:1px solid #323a46;padding:14px;white-space:pre-wrap;max-height:50vh;overflow:auto}nav{display:flex;gap:20px;flex-wrap:wrap}#artifacts{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:10px}#artifacts a{display:block;padding:12px;border:1px solid #344459;border-radius:6px;text-decoration:none;overflow-wrap:anywhere;background:#18212d}#artifacts a:hover{background:#233248}.muted,p{color:#a3aebd}.bad{color:#ef8b8b}.good{color:#78d797}.warn{color:#eac360}.summary{display:grid;grid-template-columns:160px 1fr;gap:7px;background:#171a20;border:1px solid #323a46;border-radius:6px;padding:12px;margin:14px 0}.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}#inventoryNote{white-space:pre-wrap}
</style>
<nav><a href="/">Home</a><a href="/control">Test console</a><a href="/diagnostics">Diagnostics</a><a href="/api/v1/runs">Run JSON</a></nav>
<h1>Test evidence</h1><p>Inspect diagnostic images, CSV tables, JSON, and logs inside the app. Downloads are optional. Execution, correctness, evidence, and comparison are separate outcomes.</p>
<button id="refresh">Refresh runs</button><span id="error" role="status"></span>
<table><thead><tr><th>Run</th><th>Job / variant</th><th>Execution</th><th>Correctness</th><th>Evidence</th><th>Comparison</th></tr></thead><tbody id="runs"></tbody></table>
<h2 id="selected">Select a run</h2><div id="summary" class="summary" hidden></div>
<div class="actions"><label>Find artifact <input id="artifactFilter" type="search" placeholder="Filter loaded filenames"></label><button id="moreArtifacts" hidden>Load more files</button></div>
<p id="inventoryNote" role="status"></p><div id="artifacts"></div>
<p><select id="log"><option>stdout.log</option><option>stderr.log</option><option>operator-events.jsonl</option><option>segments.jsonl</option></select> <button id="tail">Read tail</button> <label><input type="checkbox" id="follow"> Follow (1 second)</label></p>
<pre id="text">Select a file above to open its viewer, or read a bounded log tail.</pre>
<script>
const $=id=>document.getElementById(id);let run=null,busy=false,listing=false,cursor=null,files=[],epoch=0;const runResults=new Map();
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function number(v){if(v==null||!Number.isFinite(Number(v)))return '-';const text=Number(v).toFixed(2);return text==='-0.00'?'0.00':text;}
function outcome(r,name,fallback){return r.assessment?.[name]??fallback??'-'}
function cell(tr,value,cls){const td=document.createElement('td');td.textContent=value??'-';if(cls)td.className=cls;tr.append(td);return td}
function cls(v){v=String(v||'').toLowerCase();return ['completed','passed','complete','eligible'].includes(v)?'good':['crashed','failed','invalid','incomplete','ineligible','cleanupfailure','runnerfailure'].some(x=>v.includes(x))?'bad':'warn'}
async function list(){try{const rows=await json('/api/v1/runs');$('runs').replaceChildren();runResults.clear();for(const row of rows){const tr=document.createElement('tr'),r=row.Result||{},variant=r.experiment?.Variant||'';runResults.set(row.RunId,r);const first=cell(tr,row.RunId),button=document.createElement('button');button.textContent=row.RunId;first.replaceChildren(button);button.onclick=()=>select(row.RunId);first.onclick=()=>select(row.RunId);cell(tr,(r.job||r.jobPackage||'-')+(variant?' / '+variant:''));for(const [name,fallback] of [['Execution',r.status],['Correctness',r.correctnessStatus],['Evidence',r.evidenceStatus],['Comparison',r.comparisonStatus]]){const v=outcome(r,name,fallback);cell(tr,v,cls(v))}$('runs').append(tr)}$('error').textContent='';if(location.hash&&!run)await select(decodeURIComponent(location.hash.slice(1)));}catch(e){$('error').textContent=e.message}}
function addSummary(label,value){const l=document.createElement('span'),v=document.createElement('span');l.className='muted';l.textContent=label;v.textContent=value??'-';$('summary').append(l,v)}
function showArtifacts(){const filter=$('artifactFilter').value.toLowerCase();$('artifacts').replaceChildren();for(const file of files){if(filter&&!file.path.toLowerCase().includes(filter))continue;const a=document.createElement('a');a.textContent=file.path+' · '+file.bytes+' B · View';a.href='/results/view?'+new URLSearchParams({run,file:file.path});$('artifacts').append(a);}}
async function more(){if(!run||listing)return;listing=true;const selectedRun=run,version=epoch;try{const suffix=cursor?'&cursor='+encodeURIComponent(cursor):'';const page=await json('/api/v1/runs/'+encodeURIComponent(run)+'/artifacts?limit=50'+suffix);if(version!==epoch)return;if(!Array.isArray(page.items))throw Error('Artifact page is invalid.');files.push(...page.items);cursor=page.nextCursor;$('moreArtifacts').hidden=!cursor;$('inventoryNote').textContent=files.length+' files loaded'+(cursor?'; more available.':'.')+(page.complete===false?' Inventory incomplete: '+(page.issues||[]).join(', '):'')+(page.excluded?' '+page.excluded+' hidden/linked entries excluded.':'');showArtifacts();}catch(error){if(version===epoch)$('error').textContent=error.message;}finally{if(selectedRun===run)listing=false;}}
async function select(id){const version=++epoch;run=id;files=[];cursor=null;listing=false;$('artifacts').replaceChildren();$('moreArtifacts').hidden=true;$('selected').textContent=id;$('summary').replaceChildren();$('summary').hidden=false;$('text').textContent='Choose an artifact to view. No file is downloaded automatically.';try{const assessment=await json('/api/v1/runs/'+encodeURIComponent(id)+'?view=summary');if(version!==epoch)return;const r=runResults.get(id)||{};for(const name of ['Execution','Correctness','Evidence','Comparison'])addSummary(name,assessment.outcome?.[name.toLowerCase()]??outcome(r,name,r.status));addSummary('Experiment',r.experiment?.Id||'-');addSummary('Variant',r.experiment?.Variant||'-');addSummary('Comparison reasons',(assessment.reasons||r.assessment?.ComparisonReasons||[]).join('; ')||'-');addSummary('Measurements',(r.workload?.Measurements||[]).map(x=>x.Name+'='+number(x.Value)+(x.Unit?' '+x.Unit:'')).join(', ')||'-');await more();}catch(error){if(version===epoch)$('error').textContent=error.message;}}
async function tail(){if(!run||busy||document.hidden)return;busy=true;const id=run;try{const data=await json('/api/v1/runs/'+encodeURIComponent(id)+'/tail?file='+encodeURIComponent($('log').value)+'&bytes=32768');if(id===run)$('text').textContent='Bytes '+data.Offset+'..'+(data.Offset+data.Bytes)+' / '+data.FileBytes+'\n\n'+data.Text}catch(e){if(id===run)$('text').textContent=e.message}finally{busy=false}}
$('refresh').onclick=list;$('tail').onclick=tail;$('log').onchange=tail;$('moreArtifacts').onclick=more;$('artifactFilter').oninput=showArtifacts;setInterval(()=>{if($('follow').checked)tail()},1000);list();
</script></html>
""";
}
