namespace XemuTestRunner.Networking;

internal static class TestConfigurationPage
{
    public const string Html = """
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Test configurations</title><style>
body{font:15px system-ui;margin:24px;max-width:1200px}nav{display:flex;gap:16px}h1{margin-bottom:6px}.note{color:#555}button,input,textarea{font:inherit;padding:8px}button{cursor:pointer}table{border-collapse:collapse;width:100%;margin:16px 0}td,th{text-align:left;padding:9px;border-bottom:1px solid #ddd}code,pre,textarea{font-family:monospace}pre{padding:16px;background:#f4f5f7;overflow:auto;max-height:60vh}textarea{width:95%;height:200px}fieldset{margin-top:20px}#error{color:#a00;white-space:pre-wrap}
</style><nav><a href="/">Runner</a><a href="/control">Control</a><a href="/tests">Tests</a></nav>
<h1>Test configurations</h1><p class="note">Inspect a complete immutable configuration, or save a JSON configuration under a new name. Saving never starts a test.</p>
<button id="reload">Refresh</button> <button id="more" hidden>More tests</button><p id="error" role="alert"></p>
<table><thead><tr><th>Name</th><th>Revision</th><th>Steps</th><th>Description</th><th>Configuration</th></tr></thead><tbody id="rows"></tbody></table>
<h2 id="selected">Configuration viewer</h2><pre id="config">Select Inspect above.</pre><a id="download" hidden download="test-config.json">Download JSON</a>
<fieldset><legend>Upload a named configuration</legend><p><label>New name <input id="name" placeholder="vulkan-smoke"></label> <label>Asset source job <input id="source" placeholder="seed-smoke"></label></p>
<p><label>Description <input id="description"></label> <input id="file" type="file" accept=".json,application/json"></p>
<label>JobDefinition JSON<textarea id="json" spellcheck="false" placeholder='{"executable":"xemu.exe","plan":[]}'></textarea></label>
<p><label>Build files (optional, comma-separated) <input id="builds" placeholder="xemu.exe,dependency.dll"></label></p><button id="save">Save configuration only</button></fieldset>
<h2>Requested tests</h2><p class="note">Uploaded selections remain idle until Start is pressed. Queued requests wait behind the current test.</p><div id="requests"></div>
<script>
let offset=0,objectUrl=null;const $=id=>document.getElementById(id);async function api(path,body,method){const r=await fetch(path,{method:method||(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error((v.code||r.status)+': '+(v.error||'')+' '+(v.hint||''));return v}function fail(e){$('error').textContent=e.message}async function load(reset){if(reset){offset=0;$('rows').replaceChildren()}const p=await api('/api/v1/test-configs?limit=50&offset='+offset);for(const t of p.items){const tr=document.createElement('tr');for(const text of [t.id,t.revision.slice(0,12),t.stepCount,t.description]){const td=document.createElement('td');td.textContent=text;tr.append(td)}const td=document.createElement('td'),b=document.createElement('button');b.textContent='Inspect';b.onclick=()=>inspect(t).catch(fail);td.append(b);tr.append(td);$('rows').append(tr)}offset=p.nextOffset;$('more').hidden=offset===null;await requests()}async function inspect(t){const v=await api('/api/v1/test-configs/'+encodeURIComponent(t.id)+'/'+t.revision);const text=JSON.stringify(v.definition.job,null,2);$('selected').textContent=t.id+' @ '+v.revision;$('config').textContent=text;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(new Blob([text],{type:'application/json'}));$('download').href=objectUrl;$('download').download=t.id+'.json';$('download').hidden=false}async function requests(){const p=await api('/api/v1/test-runs?limit=100');$('requests').replaceChildren();for(const t of p.items){const row=document.createElement('p');row.textContent=t.id+' | '+t.testId+' | '+t.state+' ';if(t.state==='uploaded'){const b=document.createElement('button');b.textContent='Start';b.onclick=async()=>{try{await api('/api/v1/test-runs/'+encodeURIComponent(t.id)+'/start',{});await requests()}catch(e){fail(e)}};row.append(b)}if(t.result){const a=document.createElement('a');a.href=t.result;a.textContent='Result';row.append(a)}$('requests').append(row)}}
$('reload').onclick=()=>load(true).catch(fail);$('more').onclick=()=>load(false).catch(fail);$('file').onchange=async()=>{if($('file').files[0])$('json').value=await $('file').files[0].text()};$('save').onclick=async()=>{try{$('error').textContent='';const body={sourceJobId:$('source').value.trim(),description:$('description').value,job:JSON.parse($('json').value)};const paths=$('builds').value.split(',').map(s=>s.trim()).filter(Boolean);if(paths.length)body.buildFiles=paths;const saved=await api('/api/v1/test-configs/'+encodeURIComponent($('name').value.trim()),body);await load(true);await inspect(saved)}catch(e){fail(e)}};load(true).catch(fail);
</script></html>
""";
}
