using System.Globalization;

namespace XemuTestRunner.Networking;

internal static class WebPages
{
    private const string Style = """
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{font:14px/1.45 system-ui;background:#101216;color:#e7ebf0;margin:0}header{padding:18px 24px;border-bottom:1px solid #313945;display:flex;align-items:center;justify-content:space-between;gap:18px}header h1{font-size:20px;margin:0}a{color:#62a8ff;text-decoration:none}nav,.actions{display:flex;gap:10px;flex-wrap:wrap}.wrap{max-width:1450px;padding:20px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.card,.panel{background:#171a20;border:1px solid #313945;border-radius:7px;padding:14px;margin-bottom:12px}.card small,.muted{color:#a2acba}.card strong{font-size:20px;display:block}.rows{display:grid;grid-template-columns:130px 1fr;gap:7px}.badge{border:1px solid #43536b;padding:5px 9px;border-radius:5px;text-transform:uppercase}button,input{background:#232a35;border:1px solid #47556a;color:inherit;border-radius:5px;padding:8px;cursor:pointer}input{cursor:text}button:hover{border-color:#62a8ff}h2{font-size:16px;margin:0 0 10px}.layout{display:grid;grid-template-columns:minmax(300px,2fr) minmax(300px,1fr);gap:16px}.preview{aspect-ratio:4/3;background:#080a0d;display:grid;place-items:center;border:1px solid #313945}.preview img{width:100%;height:100%;object-fit:contain}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}textarea{width:100%;min-height:240px;background:#0d1015;color:#dfe5ed;border:1px solid #43536b;padding:10px;font:12px/1.5 monospace}.warning{color:#eac360}#error{color:#ef8b8b;white-space:pre-wrap}.label{color:#a2acba}@media(max-width:900px){.layout{grid-template-columns:1fr}}
</style>
""";
    private static string Page(string title, string body, string script) =>
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>" + title + "</title>" + Style +
        "</head><body><header><h1>" + title + "</h1><nav><a href=\"/\">Home</a><a href=\"/control\">Test console</a><a href=\"/results\">Evidence</a><a href=\"/api/v1/status\">Status JSON</a></nav><span id=\"phase\" class=\"badge\">Connecting</span></header><main class=\"wrap\"><div id=\"error\" role=\"status\"></div>" + body + "</main><script>" + script + "</script></body></html>";
    private const string Stats = """
<div id="stats" class="grid"></div>
<div class="panel"><h2>Current test</h2><div class="rows"><span class="label">Job</span><span id="job">-</span><span class="label">Run ID</span><span id="run">-</span><span class="label">PID / runtime</span><span id="runtime">-</span><span class="label">Queue</span><span id="queue">-</span><span class="label">Queue issue</span><span id="queueIssue">-</span><span class="label">Last result</span><span id="last">-</span><span class="label">Runner uptime</span><span id="uptime">-</span><span class="label">Sample age</span><span id="age">-</span></div></div>
<div class="panel"><h2>Workstation</h2><div class="rows"><span class="label">Session</span><span id="sessionState">-</span><span class="label">Display</span><span id="displayState">-</span><span class="label">Power</span><span id="powerState">-</span><span class="label">User idle</span><span id="userIdle">-</span><span class="label">Rendering risk</span><span id="renderRisk">-</span><span class="label">Last event</span><span id="workstationEvent">-</span></div></div>
<div class="panel"><h2>Benchmark notes</h2><div id="quality" class="warning">Not evaluated.</div><p class="muted">Preview captures, manual input, pauses and bulk transfers are logged with the run. No recorded intervention does not establish correctness or benchmark validity.</p></div>
""";
    private const string CommonJs = """
const $=id=>document.getElementById(id);let active=false;
// Round only the display. Raw telemetry, identifiers and saved evidence are unchanged.
function number(v){if(v==null||v===''||!Number.isFinite(Number(v)))return '-';const text=Number(v).toFixed(2);return text==='-0.00'?'0.00':text}
function bytes(v){if(v==null)return '-';let n=Number(v),i=0;const u=['B','KiB','MiB','GiB','TiB'];while(n>=1024&&i<4){n/=1024;i++}return n.toFixed(i?2:0)+' '+u[i]}
function pct(v){const text=number(v);return text==='-'?text:text+'%'}
function duration(ms){const s=Math.max(0,Math.floor(ms/1000));return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':')}
async function json(url,options){const r=await fetch(url,{cache:'no-store',...options});if(!r.ok)throw new Error(await r.text());return r.json()}
async function post(url,value){return json(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value??{})})}
function metric(label,value){const div=document.createElement('div');div.className='card';const small=document.createElement('small'),strong=document.createElement('strong');small.textContent=label;strong.textContent=value;div.append(small,strong);return div}
async function refresh(){try{if(document.hidden)return;const [s,q]=await Promise.all([json('/api/v1/status'),json('/api/v1/quality')]);active=!!s.CurrentJob;$('phase').textContent=s.Phase;$('job').textContent=s.CurrentJob||'-';$('run').textContent=s.RunId||'-';$('runtime').textContent=(s.ProcessId??'-')+' / '+(s.JobStartedUtc?duration(Date.now()-Date.parse(s.JobStartedUtc)):'-');$('queue').textContent='Pending '+s.Queue.Pending+' / Testing '+s.Queue.Testing+' / Tested '+s.Queue.Tested;$('queueIssue').textContent=s.QueueIssue?s.QueueIssue.Code+': '+s.QueueIssue.Message:'-';$('last').textContent=(s.LastJob||'-')+' / '+(s.LastResult||'-');$('uptime').textContent=duration(s.UptimeMs||0);const m=s.LatestMetric||{};$('age').textContent=m.TimestampUtc?Math.max(0,Date.now()-Date.parse(m.TimestampUtc))+' ms':'No current sample';const items=[['Host CPU',pct(m.HostCpuPercent)],['Process CPU (core %)',pct(m.ProcessCpuPercent)],['GPU',pct(m.GpuUtilizationPercent)],['Process GPU',pct(m.ProcessGpuUtilizationPercent)],['Host RAM',bytes(m.HostMemoryUsedBytes)+' / '+bytes(m.HostMemoryTotalBytes)],['Process RAM',bytes(m.ProcessWorkingSetBytes)],['VRAM',bytes(m.VramUsedBytes)+' / '+bytes(m.VramTotalBytes)],['Process VRAM',bytes(m.ProcessVramBytes)],['Swap / pagefile',m.SwapTotalBytes!=null?bytes(m.SwapUsedBytes)+' / '+bytes(m.SwapTotalBytes):pct(m.PageFileUsagePercent)],['Process I/O','R '+bytes(m.ProcessReadBytesPerSecond)+'/s W '+bytes(m.ProcessWriteBytesPerSecond)+'/s'],['GPU temperature/power',number(m.GpuTemperatureC)+' C / '+number(m.GpuPowerWatts)+' W'],['Collector',number(m.CollectorDurationMs)+' ms / '+pct(m.CollectorDutyPercent)+' duty'+(m.Overrun?' OVERRUN':'')]];$('stats').replaceChildren(...items.map(x=>metric(...x)));const w=s.Workstation||{};$('sessionState').textContent=!w.Supported?'unsupported':w.SessionLocked===true?'LOCKED':w.SessionLocked===false?'unlocked':'unknown';$('displayState').textContent=w.DisplayState||'unknown';$('powerState').textContent=(w.PowerState||'unknown')+' / '+(w.PowerSource||'unknown')+(w.BatteryPercent==null?'':' / '+pct(w.BatteryPercent))+(w.BatterySaver===true?' / BATTERY SAVER':'');$('userIdle').textContent=w.UserIdleSeconds==null?'-':number(w.UserIdleSeconds)+'s';$('renderRisk').textContent=w.RenderingRisk?'YES':'no';$('workstationEvent').textContent=w.LastEvent||'-';const a=q.Activity;$('quality').textContent=!a?'No active run.':a.Intervened?'Operator-intervened: '+a.ManualInputs+' input, '+a.Pauses+' pause, '+a.Screenshots+' screenshot, '+a.PreviewCaptures+' preview, '+a.BulkTransfers+' transfer operations, '+(a.Diagnostics??0)+' diagnostics, '+(a.HostStateChanges??0)+' workstation changes.':'No recorded operator intervention; comparison not evaluated.';$('error').textContent=''}catch(e){$('phase').textContent='Disconnected';$('error').textContent=e.message}finally{setTimeout(refresh,refreshMs)}}
""";
    public static string Home(int refreshMs) => Page("Xemu Test Runner", Stats,
        "const refreshMs=" + refreshMs.ToString(CultureInfo.InvariantCulture) + ";" + CommonJs + "refresh();");
    public static string Control(int refreshMs, int previewIntervalMs, bool previewEnabled) => Page("Xemu Test Console", """
<div class="layout"><section><div class="panel"><h2>Live preview</h2><div class="preview"><img id="preview" alt="No preview yet"></div><div class="actions"><button id="toggle">Toggle preview</button><button id="shot">Save screenshot</button><button id="pause">Pause</button><button id="resume">Resume</button></div><p id="previewNote" class="muted"></p></div>
""" + Stats + """
</section><aside><div class="panel"><h2>Xbox controller</h2><div id="keys" class="keys"></div><p class="actions"><input id="button" value="A" aria-label="Logical button"><input id="hold" type="number" value="100" min="1" max="60000" aria-label="Hold milliseconds" style="width:90px"><button id="send">Send</button></p><p id="provider" class="muted"></p></div>
<div class="panel"><h2>Input recorder</h2><div class="actions"><button id="record">Start recording</button><button id="stopRecord">Stop</button><button id="clearRecord">Clear</button><button id="copy">Copy plan</button></div><p id="recordState" class="muted">Manual input and retained screenshots only.</p><textarea id="plan" spellcheck="false">[]</textarea><p id="saved" class="muted"></p></div></aside></div>
""", "const refreshMs=" + refreshMs.ToString(CultureInfo.InvariantCulture) + ";const previewMs=" + previewIntervalMs.ToString(CultureInfo.InvariantCulture) +
        ";const previewAllowed=" + (previewEnabled ? "true" : "false") + ";" + CommonJs + """
let previewOn=previewAllowed,objectUrl=null,previewBusy=false;
async function operation(fn){try{await fn();$('error').textContent=''}catch(e){$('error').textContent=e.message}}
async function preview(){try{if(!previewOn||!active||document.hidden||previewBusy)return;previewBusy=true;const r=await fetch('/api/v1/preview',{cache:'no-store'});if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),url=URL.createObjectURL(blob),old=objectUrl;objectUrl=url;$('preview').src=url;if(old)URL.revokeObjectURL(old);$('previewNote').textContent='Frame '+r.headers.get('X-Captured-Utc')+' / run '+r.headers.get('X-Run-Id')}catch(e){$('previewNote').textContent=e.message}finally{previewBusy=false;setTimeout(preview,previewMs)}}
async function recording(){const r=await json('/api/v1/input/record');$('plan').value=JSON.stringify(r.Plan||[],null,2);$('recordState').textContent=r.Recording?'Recording '+r.Plan.length+' steps':'Recorder stopped';$('saved').textContent=r.SavedFile||''}
async function press(button){await post('/api/v1/input/press',{Button:button,DurationMs:Number($('hold').value)});await recording()}
for(const name of ['A','B','X','Y','Start','Back','White','Black','DPadUp','DPadDown','DPadLeft','DPadRight','LTrigger','RTrigger','LStick','RStick','LStickUp','LStickDown','LStickLeft','LStickRight','RStickUp','RStickDown','RStickLeft','RStickRight']){const b=document.createElement('button');b.textContent=name;b.onclick=()=>operation(()=>press(name));$('keys').append(b)}
$('send').onclick=()=>operation(()=>press($('button').value.trim()));$('toggle').onclick=()=>{previewOn=previewAllowed&&!previewOn;$('previewNote').textContent=previewOn?'Preview enabled; this is recorded as benchmark intervention.':'Preview disabled'};
$('pause').onclick=()=>operation(()=>post('/api/v1/xemu/pause'));$('resume').onclick=()=>operation(()=>post('/api/v1/xemu/resume'));
$('shot').onclick=()=>operation(async()=>{const r=await fetch('/api/v1/screenshot',{cache:'no-store'});if(!r.ok)throw new Error(await r.text());const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='xemu-screenshot.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);await recording()});
for(const [id,action] of [['record','start'],['stopRecord','stop'],['clearRecord','clear']])$(id).onclick=()=>operation(async()=>{await post('/api/v1/input/record/'+action);await recording()});
$('copy').onclick=()=>operation(async()=>{try{await navigator.clipboard.writeText($('plan').value)}catch{$('plan').select();document.execCommand('copy')}});
operation(async()=>{const c=await json('/api/v1/control');$('provider').textContent=(c.InputProvider||'-')+(c.InputAvailable?'':' (unavailable)');await recording()});
$('previewNote').textContent=previewAllowed?'Preview interval '+previewMs+' ms. Close or disable for benchmark runs.':'Preview disabled by config.';refresh();preview();
""");
}
