namespace XemuTestRunner.Networking;

internal static class XisoPage
{
    public const string Html = """
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>XISO campaigns</title><style>
body{font:15px system-ui;margin:24px;max-width:1200px;background:#0e1420;color:#e9edf5}a{color:#9bc5ff}nav{display:flex;gap:20px}input,select,button{font:inherit;padding:7px;margin:4px}button{cursor:pointer}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #384254}fieldset{margin:16px 0;border:1px solid #384254}pre{white-space:pre-wrap;background:#172133;padding:15px}#categories{display:flex;flex-wrap:wrap;gap:14px}#error{color:#ffb5b5}.muted{color:#aeb8c7}code{overflow-wrap:anywhere}
</style><nav><a href="/">Runner</a><a href="/tests">Saved tests</a><a href="/xiso">XISO campaigns</a></nav>
<h1>XISO campaigns</h1><p class="muted">Choose categories or individual tests. Creating a campaign does not start it. Media, defaults and test IDs are pinned before execution.</p>
<label>Suite <select id="suite"></select></label><button id="refresh">Refresh suites</button><p id="identity"></p><p id="error" role="alert"></p>
<fieldset><legend>Subsystem categories</legend><div id="categories"></div></fieldset>
<fieldset><legend>Individual tests</legend><label>Search <input id="search" placeholder="stable ID or name"></label><button id="find">Search</button><button id="more" hidden>More</button><p id="chosen" class="muted"></p>
<table><thead><tr><th>Select</th><th>Test</th><th>Category</th><th>Isolation</th></tr></thead><tbody id="tests"></tbody></table></fieldset>
<fieldset><legend>Create an unstarted campaign</legend><label>Application ID <input id="application" placeholder="build-184"></label><label>Campaign ID <input id="campaign" placeholder="pr184-shaders"></label>
<label>Mode <select id="mode"><option value="">Automatic</option value="smoke">Smoke selection</option><option value="sections">Selected sections</option><option value="full">Full coverage in chunks</option><option value="monolithic">Single process (compatible tests only)</option></select></label>
<details><summary>Optional overrides</summary><p class="muted">Blank fields inherit the saved suite defaults. No timer estimation is required.</p><label>Reference application (ABBA) <input id="reference"></label><label>Warmups <input id="warmups" type="number" min="0" max="100000"></label><label>Work multiplier <input id="multiplier" type="number" min="1" max="100000"></label></details>
<button id="create">Create only</button></fieldset>
<h2>Campaign</h2><button id="status">Refresh status</button><button id="inspect">View frozen plan</button><button id="start">Start requested campaign</button><button id="cancel">Cancel remaining tests</button><pre id="result">No campaign selected.</pre>
<script>
const $=id=>document.getElementById(id), selected=new Set();let offset=0,next=null;
async function api(path,body,method){const r=await fetch(path,{method:method||(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const v=await r.json();if(!r.ok)throw Error((v.code||r.status)+': '+(v.error||'')+' '+(v.hint||''));return v}
function fail(e){$('error').textContent=e.message}function show(v){$('result').textContent=JSON.stringify(v,null,2)}function path(){return '/api/v1/xiso-campaigns/'+encodeURIComponent($('campaign').value.trim())}
async function suites(){const page=await api('/api/v1/xiso-suites?limit=100');$('suite').replaceChildren();for(const s of page.items){const o=document.createElement('option');o.value=s.id;o.textContent=s.id+' ('+s.leafCount+' tests, '+s.qualification+')';$('suite').append(o)}if(page.nextOffset!==null)throw Error('More than 100 suites; use the paged API to select a suite.');if(page.items.length)await change();else $('identity').textContent='Register a suite from a saved template using the Python register command.'}
async function change(){selected.clear();$('chosen').textContent='0 individual tests selected';const id=encodeURIComponent($('suite').value),suite=await api('/api/v1/xiso-suites/'+id);$('identity').textContent='ISO '+suite.isoSha256+' | catalog '+suite.catalogId+' | '+suite.qualification;const cats=await api('/api/v1/xiso-suites/'+id+'/categories');$('categories').replaceChildren();for(const c of cats.items){const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=c.id;label.append(box,document.createTextNode(c.name+' ('+c.count+')'));$('categories').append(label)}await tests(true)}
async function tests(reset){if(reset){offset=0;$('tests').replaceChildren()}const q=new URLSearchParams({limit:50,offset,q:$('search').value});const page=await api('/api/v1/xiso-suites/'+encodeURIComponent($('suite').value)+'/tests?'+q);for(const t of page.items){const tr=document.createElement('tr'),td=document.createElement('td'),box=document.createElement('input');box.type='checkbox';box.checked=selected.has(t.id);box.onchange=()=>{if(box.checked)selected.add(t.id);else selected.delete(t.id);$('chosen').textContent=selected.size+' individual tests selected'};td.append(box);tr.append(td);for(const value of [t.id,t.category,t.freshProcess?'Separate process':'Route-aware chunk']){const c=document.createElement('td');c.textContent=value;tr.append(c)}$('tests').append(tr)}next=page.nextOffset;offset=next;$('more').hidden=next===null}
$('refresh').onclick=()=>suites().catch(fail);$('suite').onchange=()=>change().catch(fail);$('find').onclick=()=>tests(true).catch(fail);$('more').onclick=()=>tests(false).catch(fail);
$('create').onclick=async()=>{try{$('error').textContent='';const body={id:$('campaign').value.trim(),application:$('application').value.trim(),suite:$('suite').value};const categories=Array.from(document.querySelectorAll('#categories input:checked')).map(x=>x.value);if(categories.length)body.categories=categories;if(selected.size)body.tests=Array.from(selected);if($('mode').value)body.mode=$('mode').value;if($('reference').value.trim())body.referenceApplication=$('reference').value.trim();const settings={};if($('warmups').value!=='')settings.warmup_iterations=Number($('warmups').value);if($('multiplier').value!=='')settings.measurement_iterations_multiplier=Number($('multiplier').value);if(Object.keys(settings).length)body.settings=settings;show(await api('/api/v1/xiso-campaigns',body))}catch(e){fail(e)}};
$('status').onclick=()=>api(path()).then(show).catch(fail);$('inspect').onclick=()=>api(path()+'?view=plan').then(show).catch(fail);$('start').onclick=()=>api(path()+'/start',{}).then(show).catch(fail);$('cancel').onclick=()=>api(path(),undefined,'DELETE').then(show).catch(fail);suites().catch(fail);
</script></html>
""";
}
