<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>XemuTestRunner</AssemblyName>
    <RootNamespace>XemuTestRunner</RootNamespace>
    <VersionPrefix>0.1.0</VersionPrefix>
    <RepositoryUrl>https://github.com/Mainkill1/Xemu-Test-Runner</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RunnerChecks" />
    <InternalsVisibleTo Include="CrashChecks" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../tools/*.py">
      <Link>tools/%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
